[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
CI = "false"
GENERATE_SOURCEMAP = "false"
SKIP_PREFLIGHT_CHECK = "true"